quarkus.index-dependency.rimfrost-framework-regel-komplettering.group-id=se.fk.rimfrost.framework.regel.komplettering
quarkus.index-dependency.rimfrost-framework-regel-komplettering.artifact-id=rimfrost-framework-regel-komplettering
quarkus.index-dependency.rimfrost-referensdata-erbjudande.group-id=se.fk.rimfrost.referensdata
quarkus.index-dependency.rimfrost-referensdata-erbjudande.artifact-id=rimfrost-referensdata-erbjudande

# Container image configuration
quarkus.container-image.name=rimfrost-template-regel-komplettering

# Kafka setup
kafka.source=RegelTemplateKomplettering
kafka.subtopic=regel-template-komplettering
quarkus.kafka.devservices.topics=regel-template-komplettering-requests,regel-template-komplettering-responses,operativt-uppgiftslager-status-notification

#Incoming
mp.messaging.incoming.regel-requests.topic=regel-template-komplettering-requests

#Outgoing
mp.messaging.outgoing.regel-responses.topic=regel-template-komplettering-responses

# Persistence
quarkus.flyway.default-schema=regel_template_komplettering
regel.persistence.table-prefix=regel_template_komplettering

%prod.quarkus.datasource.username=${DB_USERNAME}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.datasource.jdbc.url=${DB_URL}

# REST setup
oul.api.base-url=http://rimfrost-k8s-uppgiftslager:8080
referensdata.api.base-url=http://rimfrost-k8s-referensdata:8080