uppgift:
  id: 99e959c9-ab62-4a8b-b5f5-655caa0140c8
  version: 1
  path: /regel/regel-template-komplettering
  aktivitet: "Komplettera regel-template"

specifikation:
  id: a42ffaed-2f20-47e8-8499-f2f79ae2f45f
  version: 1
  namn: "Komplettera saknad information"
  uppgiftbeskrivning: "Kontrollerar om yrkandet saknar obligatorisk information som behöver kompletteras av handläggaren"
  verksamhetslogik: C
  roll: ANSVARIG_HANDLAGGARE
  applikationsId: 3.5.1
  applikationsversion: regel-template_1.0

regel:
  id: a11f3429-3a6b-4389-ba1c-c2747b0fb45b
  version: 1
  namn: "Saknas obligatorisk information i yrkandet"
  beskrivning: "Kontrollerar om yrkandet innehåller all obligatorisk information och begär komplettering om något saknas"

lagrum:
  id: f0c927a9-b995-4a12-b4fd-4bcbf4281b44
  version: 1
  giltigFom: "2010-02-11"
  forfattning: "Husdjursbalken"
  kapitel: 3
  paragraf: 5
  stycke: 1
  punkt: 4

utokadUppgiftsbeskrivning:
  beskrivning: "Komplettera yrkandet med den information som saknas för att kunna fatta beslut"
